Added centos 9 environment
fullstaq-ruby/server-edition pull request #107
Opened 2022-09-13 12:13 UTC by wollistik

2022-10-09 15:17 UTC, sohooo commented
Any progress on this?

2022-11-25 11:50 UTC, FooBarWidget commented
Sorry for the late reply, I'll have a look today.

2022-11-25 11:59 UTC, FooBarWidget requested changes

2022-11-25 11:59 UTC, FooBarWidget commented on environments/centos-9/Dockerfile
> +# RUN curl -fsSLo sccache.tar.gz https://github.com/mozilla/sccache/releases/download/v0.3.0/sccache-v0.2.16-x86_64-unknown-linux-musl.tar.gz && \
sccache 0.3 is now released (latest version is 0.3.1) so we can use 0.3.1 instead of the FooBarWidget fork.

2022-11-25 11:59 UTC, FooBarWidget commented on environments/centos-9/Dockerfile
> +    dnf install -y --enablerepo epel --enablerepo powertools \
This doesn't work:

~~~
+ dnf install -y --enablerepo epel --enablerepo powertools findutils gcc gcc-c++ make patch bzip2 curl autoconf automake openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel
Error: Unknown repo: 'powertools'
~~~

But also:

~~~
No match for argument: libyaml-devel
No match for argument: gdbm-devel
~~~

2022-11-25 12:00 UTC, FooBarWidget requested changes

2022-11-25 12:00 UTC, FooBarWidget commented on environments/centos-9/Dockerfile
> +FROM rockylinux:9
Since CentOS 9 doesn't actually exist, we should call this directory `el-9` to refer to the fact that support all Enterprise Linux derivatives.

2022-11-25 12:05 UTC, FooBarWidget commented on environments/centos-9/Dockerfile
> +    dnf install -y --enablerepo epel --enablerepo powertools \
Fixed by replacing `--enablerepo powertools` with `--enablerepo devel`.

2022-11-25 12:20 UTC, FooBarWidget commented on environments/centos-9/Dockerfile
> +FROM rockylinux:9
Ruby 2.7 and 3.0 don't support the OpenSSL version included in Enterprise Linux 9, so we should exclude these Ruby versions in config.yml.

2022-11-25 12:21 UTC, FooBarWidget commented
I'm resolving the issues mentioned above.

2022-11-26 09:03 UTC, FooBarWidget commented
The EL9 issues are solved, but unrelated issues are blocking the CI (e.g. the fact that Docker Hub now requires authentication). I'm fixing those.

2022-11-27 09:03 UTC, merged

2022-11-27 09:04 UTC, FooBarWidget commented
CI issues fixed, merged to main. EL9 packages will be released when CI finishes. Thanks @wollistik

2022-11-28 11:01 UTC, wollistik commented
@FooBarWidget Thank you very much!