Adds Ruby v3.4.1 & drops Ruby 3.0
fullstaq-ruby/server-edition pull request #157
Opened 2024-12-26 01:12 UTC by san983

2024-12-28 08:02 UTC, FooBarWidget requested changes
Thanks @san983! Just one change needed.

2024-12-28 08:02 UTC, FooBarWidget commented on environments/utility/Gemfile
> +ruby '>= 3.1'
You can't bump this to 3.1. The 'utility' image is based on Ubuntu 22.04 which install Ruby from APT, which is version 3.0.

In any case, changing anything in 'environments/' also requires updating image_tag.

2025-01-01 14:25 UTC, FooBarWidget approved these changes

2025-01-01 14:25 UTC, FooBarWidget commented
I made the changes myself and I've now merged this. It will be rolled out shortly.

2025-01-01 14:25 UTC, merged

2025-01-02 07:45 UTC, FooBarWidget commented
The rollout is complete.

2025-01-03 11:56 UTC, san983 commented
> I made the changes myself and I've now merged this. It will be rolled out shortly.

Thanks a lot @FooBarWidget!